contentDir = "content"
layoutDir = "layouts"
publishDir = "dist"
buildDrafts = false
baseURL = "https://cardoe.github.io"
canonifyURLs = true
theme = "hugo-theme-bootstrap4-blog"

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    description = "Cardoe.com"
    author = "Doug Goldstein"
    twitter_username = "doug_goldstein"
