title = "Doug Goldstein"
baseURL = "https://cardoe.github.io/"
copyright = "Copyright (c) 2016 - 2017, Doug Goldstein; all rights reserved."
languageCode = "en-us"
contentDir = "content"
layoutDir = "layouts"
publishDir = "dist"
buildDrafts = false
canonifyURLs = true
theme = "hugo-theme-bootstrap4-blog"

[permalinks]
    post = "/:year/:month/:title/"
    page = "/:slug/"

[[menu.sidebar]]
    name = "GitHub"
    url = "https://github.com/cardoe/"

[taxonomies]
    category = "categories"
    tag = "tags"

[params]
    description = "Mostly Programming and Virtualization"
    author = "Doug Goldstein"

    [params.sidebar]

    [params.social]
    twitter = "doug_goldstein"

    [params.sharingicons]
    hide = true
